# Absolute waypoint for moving_turtle
float32 x
float32 y
---
# Time required to reach the waypoint
builtin_interfaces/Duration duration
---
# Remaining Euclidean distance to the waypoint
float32 distance
